services:
  bot:
    container_name: peacemaker-bot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WEBHOOK_PROXY_URL=${WEBHOOK_PROXY_URL}
        - APP_ID=${APP_ID}
        - PRIVATE_KEY=${PRIVATE_KEY}
        - WEBHOOK_SECRET=${WEBHOOK_SECRET}
        - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
        - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
        - PERSPECTIVE_API_KEY=${PERSPECTIVE_API_KEY}
        - DISCOVERY_URL="https://commentanalyzer.googleapis.com/$discovery/rest?version=v1alpha1"
        - GROQ_API_KEY=${GROQ_API_KEY}
        - MONGODB_URI=${MONGODB_URI}
        - MONGODB_DB=${MONGODB_DB}
    env_file:
      - '.env'
    ports:
      - '4000:4000'
