services:
  peacemaker-bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - LOG_LEVEL=${LOG_LEVEL:-debug}
        - WEBHOOK_PROXY_URL=${WEBHOOK_PROXY_URL}
        - APP_ID=${APP_ID}
        - WEBHOOK_SECRET=${WEBHOOK_SECRET}
        - PRIVATE_KEY=${PRIVATE_KEY}
        - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
        - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
        - PERSPECTIVE_API_KEY=${PERSPECTIVE_API_KEY}
        - MONGODB_URI=${MONGODB_URI}
        - PORT=${PORT:-4000}

    env_file:
      - '.env'
    ports:
      - '4000:4000'
