# fly.toml app configuration file generated for peacemaker-bot on 2025-01-18T00:40:24-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'peacemaker-bot'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
