const TOXICITY_THRESHOLD = 0.6;
const DISCOVERY_URL = process.env.DISCOVERY_URL;
const PERSPECTIVE_API_KEY = process.env.PERSPECTIVE_API_KEY;
const MONGODB_URI = process.env.MONGODB_URI;
const MONGODB_DB = process.env.MONGODB_DB;

module.exports = {
  TOXICITY_THRESHOLD,
  DISCOVERY_URL,
  PERSPECTIVE_API_KEY,
  MONGODB_URI,
  MONGODB_DB,
};
